In [2]:
# array 函数 → 创建具有维度属性的向量
a <- array(c(1, 2, 3, 4, 5, 6, 7, 8, 9 ,10, 11, 12), dim = c(3, 4))
# 从 1 开始

In [3]:
a

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [4]:
# 取元素
# a[行， 列]
a[2, 2]

[1] 5

In [8]:
a[1:2, 1:2]

[,1] [,2]
[1,] 1    4   
[2,] 2    5

In [9]:
a[1, ]

[1]  1  4  7 10

In [5]:
# 矩阵
m <- matrix(data = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
           nrow = 3, ncol = 4)

In [10]:
m

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [11]:
# data frame

In [12]:
teams <- c("PIN", "MYM", "FLA", "ATL", "WSN")
w <- c(92, 89, 94, 72, 59)
l <- c(70, 73, 77, 90, 102)
nleast <- data.frame(teams, w, l)

In [13]:
nleast

teams w  l  
1 PIN   92  70
2 MYM   89  73
3 FLA   94  77
4 ATL   72  90
5 WSN   59 102