In [1]:
import numpy as np

In [5]:
a = np.arange(16)

In [7]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
a.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
# np.round()
# 用于对数组或单个数值进行四舍五入,该函数返回一个与输入类型相同的数组或数值,
# 并可以通过可选的参数来指定保留的小数位数
np.round([1.2233, 1.34]) 

array([1., 1.])

In [8]:
np.round([1.2233, 1.34], decimals=1) 

array([1.2, 1.3])